# Generated by Django 2.1.5 on 2019-02-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ooglorp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='address',
            field=models.CharField(default='Carnegie Mellon', max_length=1000),
        ),
        migrations.AddField(
            model_name='food',
            name='key',
            field=models.CharField(default='asdf', max_length=1200),
        ),
    ]
