# Generated by Django 2.1.5 on 2019-02-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ooglorp', '0002_auto_20190209_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='phone',
            field=models.CharField(default='111-111-1111', max_length=15),
        ),
    ]
